config github ec2 workflows 3

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -54,27 +54,22 @@ jobs:
         run: |
           ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
             echo "Updating EC2 instance..."
-            sudo dnf update -y
-          
-            echo "Installing Docker..."
-            sudo dnf install -y docker
+            sudo yum update -y
+
+            echo "Installing required tools: Git, Docker..."
+            sudo yum install -y git docker
             sudo systemctl start docker
             sudo systemctl enable docker
             sudo usermod -aG docker ec2-user
-            newgrp docker <<EOF
-            echo "Pulling the Docker image..."
-            docker stop rest-api-java || true
-            docker rm rest-api-java || true
-            docker pull ${{ secrets.DOCKER_USERNAME }}/rest-api-java:latest
-            echo "Running the Docker container..."
-            docker run -d --name rest-api-java -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/rest-api-java:latest
-            EOF
-          
-            echo "Pulling the Docker image..."
-            docker stop rest-api-java || true
-            docker rm rest-api-java || true
-            docker pull ${{ secrets.DOCKER_USERNAME }}/rest-api-java:latest
-          
-            echo "Running the Docker container..."
-            docker run -d --name rest-api-java -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/rest-api-java:latest
+
+            # Recargar permisos del grupo Docker
+            newgrp docker <<INNER_EOF
+              echo "Pulling the Docker image..."
+              docker stop rest-api-java || true
+              docker rm rest-api-java || true
+              docker pull ${{ secrets.DOCKER_USERNAME }}/rest-api-java:latest
+
+              echo "Running the Docker container..."
+              docker run -d --name rest-api-java -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/rest-api-java:latest
+            INNER_EOF
           EOF
